### ISSUE TITLE
Loading issue

### ISSUE THREAD

**Issue by LiteApplication** [imknown/AndroidLowLevelDetector#4]
I had an issue when I opened LLD for the first time after a while, the app encountered an error and couldn't load the main page even with Online data disabled.
A reinstallation fixed the bug.

**Comment by imknown** [comment]
Can you provide the error message? I will check it out.
It sounds like that your client version is old, which cannot parse the latest format online data.

**Comment by LiteApplication** [comment]
Yes , the app told me that be when I went to play store, I didn't have update so it's why I uninstall reinstall

**Comment by LiteApplication** [comment]
The message was about parsing

**Comment by imknown** [comment]
@LiteApplication What is your client app version before you uninstalled? Sometimes the Google Play App `Storage cache` may cause the update checking not working. I met once. The `1.4.3` was released but the Google Play App told me that `1.4.2` was the latest. After I cleared the Google Play App storage cache, I received the latest `1.4.3`, strange.

For this app, you can try `App Info` - `Storage & cache` - `Clear storage` to revoke the Online incompatible online data insteading of uninstalling-reinstalling. It will turn off the online switch and use the built-in bundle data.

The update logic is still need to improve. I will separate the parsing logic in the future versions which means the data will not depend on the client app version.

**Comment by LiteApplication** [comment]
Ok, thank you 😉

**Comment by imknown** [comment]
Hi, I refactored the whole app fetching/loading/parsing/saving logic days before.
I think this issue has been corrected already.
I will release 1.11.0 beta to test it soon.

> https://github.com/imknown/AndroidLowLevelDetector/commit/7fdbe776c3c8d73bc1f38ae1a802e3125e005bfe
> https://github.com/imknown/AndroidLowLevelDetector/commit/44402072723968ca2789010b142b58efd0c94d58
> https://github.com/imknown/AndroidLowLevelDetector/commit/9e133e0f2df036b8535d3c4238a4103e8c003f67
